### ISSUE TITLE
Fuel App Web page errors on page open/refresh, tank number selection, interface update, etc...

### ISSUE THREAD

**Issue by donc310** [donc310/vue-graph-template#26]
The first error is from page open/refresh
The second error is from tank number dropdown list
The third and fourth errors are from updating the sensor interface
Note: The Energy App Web page somehow has no new error as Fuel App even though both had the same changes.
Update: The Energy App does have issue with updating Data Source Filename entry. Other entries seem to be Ok.

![Image](https://user-images.githubusercontent.com/112269236/188543214-61339b6a-2a62-42a2-ba06-456fa22424ff.png)

![Image](https://user-images.githubusercontent.com/112269236/188683710-fd8b851e-dd08-48e8-b2a4-3b09fdc00b97.png)

**Comment by tqchiem** [comment]
is this fixed?.

**Comment by donc310** [comment]
@tqchiem  yes issue has been resoved with the last commit

**Comment by tqchiem** [comment]
Web page opens with "404 Not Found" code, so cannot verify these errors

**Comment by tqchiem** [comment]
This is fixed.
